### ISSUE TITLE
Issue with Reshade running with CeMu

### ISSUE THREAD

**Issue by HEspoke** [crosire/reshade#16]
Hey guys, 
Could you please check out this post and get back to me on your thoughts on a possible solution. I would appreciate it. Keep up the great work with Reshade. Thanks.
https://www.reddit.com/r/cemu/comments/6ndb26/super_mario_3d_world_shows_messed_up_shadows_with/

**Comment by Fs00** [comment]
I created a thread on the official forum where I posted all the issues that I found using ReShade with Cemu, if it can help. Your bug, @HEspoke, is in that thread as well: [reshade.me/forum/troubleshooting/3493-cemu-bug-reporting-thread-last-updated-21-08-17](https://reshade.me/forum/troubleshooting/3493-cemu-bug-reporting-thread-last-updated-21-08-17)

**Comment by Fs00** [comment]
@crosire Any words on those issues? Are you looking into them?
@HEspoke I suggest to you to rename this issue "Issue**s** with Reshade running with Cemu".
