### ISSUE TITLE
Change Request: Remove network check on depth effects

### ISSUE THREAD

**Issue by KairuByte** [crosire/reshade#18]
If I recall correctly, this was added on the premise that depth effects could be used to cheat in an online game, giving unfair advantage. This was bypassed at one point with a closed source tool, and now it takes just one line of code being commented out to compile without the check.

Can this _please_ be officially removed? Or might there be a way to check what application is being run, and create a whitelist for specific games where this is known to be acceptable?

My reasoning is this: Cheaters are already injecting into games using tools specifically built to do exactly what is most beneficial, and adding an effect using reshade, no matter what it might be or how complex they make it, would pale in comparison to those deliberately crafted tools.

**Comment by crosire** [comment]
No. Officially distributed binaries are distinguishable from those compiled without the check, as such anti-cheat tools can whitelist the official version, but will continue to block modified versions that could provide an unfair advantage.
