### ISSUE TITLE
Still a dependency on Vulkan in the project files

### ISSUE THREAD

**Issue by FransBouma** [crosire/reshade#2]
Building reshade (no matter the output type) gives: 

`LINK : fatal error LNK1104: cannot open file '\Bin\vulkan-1.lib'`

Looking into where this is referenced:
```
C:\Users\user\Documents\GitHub\reshade>dir /s /b *.* | findstr /f:/ "vulkan-1.lib"
C:\Users\user\Documents\GitHub\reshade\deps\Vulkan.props:      <AdditionalDependencies Condition="'$(Platform)' == '
Win32'">$(VK_SDK_PATH)\Bin32\vulkan-1.lib;%(AdditionalDependencies)</AdditionalDependencies>
C:\Users\user\Documents\GitHub\reshade\deps\Vulkan.props:      <AdditionalDependencies Condition="'$(Platform)' == '
x64'">$(VK_SDK_PATH)\Bin\vulkan-1.lib;%(AdditionalDependencies)</AdditionalDependencies>
```

Vulkan.props is in the vcxproj, line 52
```xml
<ImportGroup Label="PropertySheets">
    <Import Project="$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props" Condition="exists('$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props')" Label="LocalAppDataPlatform" />
    <Import Project="deps\Vulkan.props" />
```

This props file can be removed?

**Comment by FransBouma** [comment]
Commenting the deps\Vulkan.props line makes the project compile. I saw in the commit history you removed vulkan/dx12 so I guess this is a leftover. If so I'll send you a PR

**Comment by crosire** [comment]
Yeah, it's a leftover. Solved either by removing the props file or installing the Vulkan SDK. Will remove it real quickly.
