### ISSUE TITLE
Compatibility: D3D9 Video Swapchains

### ISSUE THREAD

**Issue by Kaldaien** [crosire/reshade#23]
In my fork of ReShade, I have disabled the D3D9 runtime for video-only swapchains.

This is a useful compatibility change for many D3D11 and GL games that use DXVA and pull-in D3D9 for no other reason than to hardware accelerate video playback through D3D9Ex.

I wanted to run by the option of skipping runtime initialization on D3D9 devices created with **pPresentationParameters->Flags & D3DPRESENTFLAG_VIDEO**.

```
HRESULT STDMETHODCALLTYPE IDirect3D9Ex_CreateDeviceEx(IDirect3D9Ex *pD3D, UINT Adapter, D3DDEVTYPE DeviceType, HWND hFocusWindow, DWORD BehaviorFlags, D3DPRESENT_PARAMETERS *pPresentationParameters, D3DDISPLAYMODEEX *pFullscreenDisplayMode, IDirect3DDevice9Ex **ppReturnedDeviceInterface)
{
...
	const HRESULT hr = reshade::hooks::call(&IDirect3D9Ex_CreateDeviceEx)(pD3D, Adapter, DeviceType, hFocusWindow, BehaviorFlags, pPresentationParameters, pFullscreenDisplayMode, ppReturnedDeviceInterface);

	if (pPresentationParameters->Flags & D3DPRESENTFLAG_VIDEO)
	{
		LOG(WARNING) << "> Skipping device due to video swapchain.";
		return hr;
	}
```

Given very little test content or familiarity with this project, I blanket disabled the ReShade runtime for D3D9 video swapchains. This fixes stability issues where ReShade unnecessarily begins hooking D3D9 for the title videos in Hyper Dimension Neptunia, Fairy Fencer F and Akiba's Trip.

I do not know if it is going to change the user's experience in any way and I see no compatibility options like this anywhere. Perhaps you know if video swapchains factor into the current post-process pipeline or if universally ignoring them is appropriate?

**Comment by crosire** [comment]
It'd should be fine to universally ignore them. Can always revert the change should it cause issues.
If you want you could create a pull request with those modifications.
