### ISSUE TITLE
Winsock hooks calling WSASend* for calls that originated as send*

### ISSUE THREAD

**Issue by blattersturm** [crosire/reshade#24]
In [source/windows/ws2_32.cpp](https://github.com/crosire/reshade/blob/14d54cf5043eeabe936ba08062c78dc1b16d4e58/source/windows/ws2_32.cpp#L80), there's hooks for functions such as `recv`, `recvfrom`, `send` and `sendto`.

However, instead of chaining to the original functions, these chain down to the original WSA\* functions, which breaks certain applications that do hook WinSock functions themselves, such as [FiveM](https://github.com/citizenfx/fivem/blob/c8aa10c757c8e57a2f2ed248afdba2836fb7b4b0/code/components/ros-patches-five/src/ros/LoopbackTcpServer.cpp#L770).

I do not see why a graphics modification would need to hook WinSock functions (tracking a count of calls made - why?!), nor why it would (intentionally?) alter behavior of calls to APIs made by applications.

**Comment by crosire** [comment]
ReShade needs to track network traffic in order for it to disable depth access in online games.
The rerouting to WSA function variants is done soly for code simplification.
