### ISSUE TITLE
Some thing about Post processing order.

### ISSUE THREAD

**Issue by kxzxxx** [crosire/reshade#26]
I am thinking if it can apply effect beforce game effect?
Because some game use in-game fxaa blur screen. 
If reshade apply sharpeness before in-game fxaa, it will clear up some blur.

> HRESULT STDMETHODCALLTYPE DXGISwapChain::Present(UINT SyncInterval, UINT Flags)
> {
> //hook
> return _orig->Present(SyncInterval, Flags);
> }

> HRESULT STDMETHODCALLTYPE DXGISwapChain::Present(UINT SyncInterval, UINT Flags)
> {
> HRESULT hr = _orig->Present(SyncInterval, Flags);
> //hook
> return hr;
> }

**Comment by crosire** [comment]
ReShade cannot detect where in the frame the game does post-processing (at least on generically), so this is not possible.
