### ISSUE TITLE
I have issues when building the OpenVR branch of reshade.  openvr.h

### ISSUE THREAD

**Issue by BlueSkyDefender** [crosire/reshade#27]
The error is 

"7>c:\users\untou\source\repos\reshade\source\d3d11\d3d11_runtime.cpp(14): fatal error C1083: Cannot open include file: 'openvr.h': No such file or directory"

So I ended up going to https://github.com/ValveSoftware/openvr/tree/master/headers and added them my self to the folder to build it.

Feels Like I made a mistake. I am new to this so this is hard for me.

Also had to the same thing with openvr_api.lib. 

But, once I added the files from Valves git hub it compiled.

 I think I did it the wrong way.

**Comment by crosire** [comment]
See step 1 in the building instructions: You need to clone all Git submodules as well. The OpenVR SDK is pulled in as a submodule. This can be done with `git submodule update`.

**Comment by BlueSkyDefender** [comment]
I will do that. I am just new to this :).

------------------------------------------------------------------------------------------------------------------
When using the reshade.dll, I also had to place openvr_api.dll in the game folder alongside it. Once I did that I work really well.  

I have to ask is this a by-product of my incorrectly building the file?

I am impressed with this. I also have to update my shaders to support the IPD adjusted values.  It seems to be around -250 to -400. 

Thank you again for your hard work.

**Comment by crosire** [comment]
Yeah, putting the OpenVR DLL in the game folder is required. One way around that would be to put it in the system directory I suppose.

**Comment by BlueSkyDefender** [comment]
It worked 👍 
git submodule update --init

The IPD adjustment seems to be -350 for the Oculus Rift in the shader. With your HTC Vive can you confirm if IPD setting close/good for you?

https://github.com/BlueSkyDefender/Depth3D/blob/master/Shaders/Alternative%20Shaders/Experimental/Polynomial_Barrel_Distortion_v1.2.fx

When you have time. Thank you.

**Comment by crosire** [comment]
With the Vive I used a value of 40 (in GTA V).
