### ISSUE TITLE
Error compiling SMAA under OpenGL

### ISSUE THREAD

**Issue by bacondither** [crosire/reshade#28]
SMAA does not compile under OpenGL anymore. The problem started after commit https://github.com/crosire/reshade/commit/e2c4a7cae00214eba19fbc1bc22c7e38e3860042. Testing was done with an AMD GPU.

Log snippet: [logError.txt](https://github.com/crosire/reshade/files/1327690/logError.txt)

**Comment by crosire** [comment]
SMAA compiles again now, but it seems like something is still broken, because the blend-weight calculation pass doesn't output anything.
