### ISSUE TITLE
PUBG: Reshade crashes with Dxtpory

### ISSUE THREAD

**Issue by SkippTekk** [crosire/reshade#29]
So, i have been using Dxtory for a long time. and the game likes to crash before it starts. i have the latest version of Shaders. But i found a temp salution. Load game first, then load Dxtory. no crash logs yet to be found..

Maybe im looking at the wrong place?

Dxtory Version: 2.0.142
Reshade 3.0.8

**Comment by SkippTekk** [comment]
So it looks like this program isn't being watched by the devs. when this stuff shouldn't be happening. cool

**Comment by crosire** [comment]
Please use https://reshade.me/forum/troubleshooting. Also, ReShade makes no guarantees on compatibility with other third party overlay software, since they involve similar techniques that are often not working together.
