### ISSUE TITLE
D3D11 using game could crash with debug build

### ISSUE THREAD

**Issue by FransBouma** [crosire/reshade#3]
(I'm testing with The Witcher 3, x64, dx11 on windows 8.1 x64)

Release builds of reshade work, debug builds crash when window is created. Turns out these two lines: 
https://github.com/crosire/reshade/blob/master/source/d3d11/d3d11.cpp#L25-L26
cause it to crash. Commenting them out fixes it. 

Not sure whether these two lines are needed.

**Comment by crosire** [comment]
The first flag is pretty useful when debugging. You need the D3D debug runtime / SDK layers for it to work though. And some games don't like the debug runtime very much. So (un-)comment those lines as needed for the particular game you are debugging.

**Comment by FransBouma** [comment]
Ah makes sense :)
