### ISSUE TITLE
Is it possible to prevent reshade dlls from hooking to an executable?

### ISSUE THREAD

**Issue by Nik-Lz** [crosire/reshade#33]
In my target directory i have two executables. One is the game i want to use with reshade. That's alright. The other is a tool and i want to prevent the dlls from hooking into that program as well. However i can't put it in another directory because it depends on executable No1 - the game. Is it possible to prevent reshade from hooking to a specified executable?

**Comment by crosire** [comment]
The only way to do that in the moment is to inject the ReShade DLL into the target process with a corresponding tool on startup instead of putting it in the game directory so the game loads it itself.
