### ISSUE TITLE
Feature Request: Command Line Options

### ISSUE THREAD

**Issue by LeeThompson** [crosire/reshade#5]
(I'll add this myself as a pull request if I have time but here it is anyway.)

I'd like to see some command line options for some automation, here are some examples:

`--update [keyword]`

Where "keyword" can be "`all`" (default), "`program`" or "`shaders`".
Example: `--update shaders` would make sure your shaders/textures are current.

`--add pathname api`

Add Reshade to given pathname (i.e. `--add "C:\Games\My Game\game.exe" dx9`)

`--remove pathname`

Remove ReShade from game.  (Might need to supply the api).

**Comment by el3ment** [comment]
`--loglevel` would also be nice!

**Comment by crosire** [comment]
A commandline API for the setup tool sounds useful, I agree. I don't see what `--loglevel` would do since it doesn't log anything though.

**Comment by crosire** [comment]
You can now do an automatic installation without user interaction via:
`"ReShade Setup.exe" "Game.exe" --api opengl --headless`
