### ISSUE TITLE
ReShade 3.0.6 Does Not Work With WildStar

### ISSUE THREAD

**Issue by LeeThompson** [crosire/reshade#6]
3.0.5 and earlier worked with WildStar (MMORPG from NCSoft), 3.0.6 no longer works.

(DirectX 11, x64)

The dxgi.log doesn't even get created for some reason.    Also tried the dx9 replacement, same result.

(Game site http://www.wildstar-online.com/)

**Comment by LeeThompson** [comment]
I don't know quite why or how but I moved my ReShade .ini files and stuff out of WildStar's folder and re-ran the setup tool.    The initialization display showed up again, I put my old inis back in and it still works.

The dxgi.dll appears to be different, not sure what happened there.

**Comment by crosire** [comment]
That's the 64-bit instead of the 32-bit build. 3.0.6 didn't change anything in the D3D11 rendering backend, so it would not make sense to work differently.
