### ISSUE TITLE
Not working with BF4 x64 Windows 10

### ISSUE THREAD

**Issue by Benji-13** [crosire/reshade#7]
ReShade 3.0.6 is not working on Battlefield 4. I am running the x64 game on an x64 version of windows 10. I have disabled the orign overlay. I do not have MSI Afterburner or FRAPPS ect. I have disabled Nvidia Geforce Experience. I chose Direct3D 10+ when installing. I have the DirectX End user thingy. When I start the game (online and offline) I almost immediately get a 'BF4 has stopped working' error. The dgxi.dll log says:

05/01/2017 18:05:04:375 [08444] | INFO | Initializing crosire's ReShade version '3.0.6.165' (64-bit) built on '2017-01-01 17:00:05' loaded from 'C:\Program Files (x86)\Origin Games\Battlefield 4\dxgi.dll' to 'C:\Program Files (x86)\Origin Games\Battlefield 4\bf4.exe' ...
05/01/2017 18:05:04:376 [08444] | INFO | Installing hook for '0x00007FFE4224F610' with '0x00007FFE0F806390' using method 1 ...
05/01/2017 18:05:04:390 [08444] | INFO | > Succeeded.
05/01/2017 18:05:04:390 [08444] | INFO | Installing hook for '0x00007FFE4224EC40' with '0x00007FFE0F806610' using method 1 ...
05/01/2017 18:05:04:404 [08444] | INFO | > Succeeded.
05/01/2017 18:05:04:404 [08444] | INFO | Installing hook for '0x00007FFE4224ED90' with '0x00007FFE0F8066B0' using method 1 ...
05/01/2017 18:05:04:422 [08444] | INFO | > Succeeded.
05/01/2017 18:05:04:422 [08444] | INFO | Installing hook for '0x00007FFE42249BF0' with '0x00007FFE0F806930' using method 1 ...
05/01/2017 18:05:04:435 [08444] | INFO | > Succeeded.
05/01/2017 18:05:04:435 [08444] | INFO | Registering hooks for 'C:\WINDOWS\system32\d3d9.dll' ...
05/01/2017 18:05:04:436 [08444] | INFO | > Delayed.
05/01/2017 18:05:04:436 [08444] | INFO | Registering hooks for 'C:\WINDOWS\system32\d3d10.dll' ...
05/01/2017 18:05:04:437 [08444] | INFO | > Delayed.
05/01/2017 18:05:04:437 [08444] | INFO | Registering hooks for 'C:\WINDOWS\system32\d3d10_1.dll' ...
05/01/2017 18:05:04:437 [08444] | INFO | > Delayed.
05/01/2017 18:05:04:437 [08444] | INFO | Registering hooks for 'C:\WINDOWS\system32\d3d11.dll' ...
05/01/2017 18:05:04:438 [08444] | INFO | > Delayed.
05/01/2017 18:05:04:438 [08444] | INFO | Registering hooks for 'C:\WINDOWS\system32\dxgi.dll' ...
05/01/2017 18:05:04:438 [08444] | INFO | > Delayed.
05/01/2017 18:05:04:438 [08444] | INFO | Registering hooks for 'C:\WINDOWS\system32\opengl32.dll' ...
05/01/2017 18:05:04:439 [08444] | INFO | > Delayed.
05/01/2017 18:05:04:439 [08444] | INFO | Registering hooks for 'C:\WINDOWS\system32\user32.dll' ...
05/01/2017 18:05:04:439 [08444] | INFO | > Libraries loaded.
05/01/2017 18:05:04:439 [08444] | INFO | > Dumping matches in export table:
05/01/2017 18:05:04:439 [08444] | INFO | +
+
+
+
05/01/2017 18:05:04:439 [08444] | INFO | | Address | Ordinal | Name |
05/01/2017 18:05:04:439 [08444] | INFO | +
+
+
+
05/01/2017 18:05:04:440 [08444] | INFO | | 0x00007FFE408171B0 | 1822 | GetCursorPos |
05/01/2017 18:05:04:440 [08444] | INFO | | 0x00007FFE4080E8B0 | 1884 | GetMessageA |
05/01/2017 18:05:04:440 [08444] | INFO | | 0x00007FFE40814840 | 1888 | GetMessageW |
05/01/2017 18:05:04:440 [08444] | INFO | | 0x00007FFE4080E300 | 2155 | PeekMessageA |
05/01/2017 18:05:04:440 [08444] | INFO | | 0x00007FFE4080E430 | 2156 | PeekMessageW |
05/01/2017 18:05:04:440 [08444] | INFO | | 0x00007FFE40815210 | 2201 | RegisterClassA |
05/01/2017 18:05:04:440 [08444] | INFO | | 0x00007FFE40887F40 | 2202 | RegisterClassExA |
05/01/2017 18:05:04:440 [08444] | INFO | | 0x00007FFE407FAC60 | 2203 | RegisterClassExW |
05/01/2017 18:05:04:440 [08444] | INFO | | 0x00007FFE407FAEA0 | 2204 | RegisterClassW |
05/01/2017 18:05:04:440 [08444] | INFO | | 0x00007FFE40823EB0 | 2221 | RegisterRawInputDevices |
05/01/2017 18:05:04:440 [08444] | INFO | | 0x00007FFE4081BBF0 | 2276 | SetCursorPos |
05/01/2017 18:05:04:440 [08444] | INFO | +
+
+
+
05/01/2017 18:05:04:440 [08444] | INFO | > Found 11 match(es). Installing ...
05/01/2017 18:05:04:440 [08444] | INFO | Installing hook for '0x00007FFE408171B0' with '0x00007FFE0F893000' using method 1 ...
05/01/2017 18:05:04:454 [08444] | INFO | > Succeeded.
05/01/2017 18:05:04:454 [08444] | INFO | Installing hook for '0x00007FFE4080E8B0' with '0x00007FFE0F892B80' using method 1 ...
05/01/2017 18:05:04:467 [08444] | INFO | > Succeeded.
05/01/2017 18:05:04:467 [08444] | INFO | Installing hook for '0x00007FFE40814840' with '0x00007FFE0F892C50' using method 1 ...
05/01/2017 18:05:04:482 [08444] | INFO | > Succeeded.
05/01/2017 18:05:04:482 [08444] | INFO | Installing hook for '0x00007FFE4080E300' with '0x00007FFE0F892D20' using method 1 ...
05/01/2017 18:05:04:495 [08444] | INFO | > Succeeded.
05/01/2017 18:05:04:495 [08444] | INFO | Installing hook for '0x00007FFE4080E430' with '0x00007FFE0F892E00' using method 1 ...
05/01/2017 18:05:04:509 [08444] | INFO | > Succeeded.
05/01/2017 18:05:04:509 [08444] | INFO | Installing hook for '0x00007FFE40815210' with '0x00007FFE0F892160' using method 1 ...
05/01/2017 18:05:04:524 [08444] | INFO | > Succeeded.
05/01/2017 18:05:04:524 [08444] | INFO | Installing hook for '0x00007FFE40887F40' with '0x00007FFE0F892420' using method 1 ...
05/01/2017 18:05:04:537 [08444] | INFO | > Succeeded.
05/01/2017 18:05:04:537 [08444] | INFO | Installing hook for '0x00007FFE407FAC60' with '0x00007FFE0F892580' using method 1 ...
05/01/2017 18:05:04:551 [08444] | INFO | > Succeeded.
05/01/2017 18:05:04:551 [08444] | INFO | Installing hook for '0x00007FFE407FAEA0' with '0x00007FFE0F8922C0' using method 1 ...
05/01/2017 18:05:04:564 [08444] | INFO | > Succeeded.
05/01/2017 18:05:04:564 [08444] | INFO | Installing hook for '0x00007FFE40823EB0' with '0x00007FFE0F8926E0' using method 1 ...
05/01/2017 18:05:04:580 [08444] | INFO | > Succeeded.
05/01/2017 18:05:04:580 [08444] | INFO | Installing hook for '0x00007FFE4081BBF0' with '0x00007FFE0F892EE0' using method 1 ...
05/01/2017 18:05:04:595 [08444] | INFO | > Succeeded.
05/01/2017 18:05:04:596 [08444] | INFO | Registering hooks for 'C:\WINDOWS\system32\ws2_32.dll' ...
05/01/2017 18:05:04:596 [08444] | INFO | > Delayed.
05/01/2017 18:05:04:596 [08444] | INFO | Initialized.
05/01/2017 18:05:04:597 [08444] | INFO | Installing delayed hooks for 'C:\WINDOWS\system32\d3d11.dll' (Just loaded via 'LoadLibraryA("d3d11.dll")') ...
05/01/2017 18:05:04:597 [08444] | INFO | > Dumping matches in export table:
05/01/2017 18:05:04:597 [08444] | INFO | +
+
+
+
05/01/2017 18:05:04:597 [08444] | INFO | | Address | Ordinal | Name |
05/01/2017 18:05:04:597 [08444] | INFO | +
+
+
+
05/01/2017 18:05:04:597 [08444] | INFO | | 0x00007FFE3C1F5080 | 22 | D3D11CreateDevice |
05/01/2017 18:05:04:597 [08444] | INFO | | 0x00007FFE3C1F5170 | 23 | D3D11CreateDeviceAndSwapChain |
05/01/2017 18:05:04:597 [08444] | INFO | +
+
+
+
05/01/2017 18:05:04:597 [08444] | INFO | > Found 2 match(es). Installing ...
05/01/2017 18:05:04:598 [08444] | INFO | Installing hook for '0x00007FFE3C1F5080' with '0x00007FFE0F850F30' using method 1 ...
05/01/2017 18:05:04:613 [08444] | INFO | > Succeeded.
05/01/2017 18:05:04:613 [08444] | INFO | Installing hook for '0x00007FFE3C1F5170' with '0x00007FFE0F8511B0' using method 1 ...
05/01/2017 18:05:04:627 [08444] | INFO | > Succeeded.
05/01/2017 18:05:04:633 [08444] | INFO | Installing delayed hooks for 'C:\WINDOWS\system32\ws2_32.dll' (Just loaded via 'LoadLibraryA("WS2_32.dll")') ...
05/01/2017 18:05:04:633 [08444] | INFO | > Dumping matches in export table:
05/01/2017 18:05:04:633 [08444] | INFO | +
+
+
+
05/01/2017 18:05:04:633 [08444] | INFO | | Address | Ordinal | Name |
05/01/2017 18:05:04:633 [08444] | INFO | +
+
+
+
05/01/2017 18:05:04:633 [08444] | INFO | | 0x00007FFE40B2BDB0 | 91 | WSARecv |
05/01/2017 18:05:04:633 [08444] | INFO | | 0x00007FFE40B37640 | 93 | WSARecvFrom |
05/01/2017 18:05:04:633 [08444] | INFO | | 0x00007FFE40B2B920 | 96 | WSASend |
05/01/2017 18:05:04:633 [08444] | INFO | | 0x00007FFE40B38D00 | 99 | WSASendTo |
05/01/2017 18:05:04:633 [08444] | INFO | | 0x00007FFE40B2AFC0 | 16 | recv |
05/01/2017 18:05:04:633 [08444] | INFO | | 0x00007FFE40B380F0 | 17 | recvfrom |
05/01/2017 18:05:04:633 [08444] | INFO | | 0x00007FFE40B2C520 | 19 | send |
05/01/2017 18:05:04:633 [08444] | INFO | | 0x00007FFE40B2EA80 | 20 | sendto |
05/01/2017 18:05:04:633 [08444] | INFO | +
+
+
+
05/01/2017 18:05:04:633 [08444] | INFO | > Found 8 match(es). Installing ...
05/01/2017 18:05:04:633 [08444] | INFO | Installing hook for '0x00007FFE40B2BDB0' with '0x00007FFE0F8932B0' using method 1 ...
05/01/2017 18:05:04:647 [08444] | INFO | > Succeeded.
05/01/2017 18:05:04:647 [08444] | INFO | Installing hook for '0x00007FFE40B37640' with '0x00007FFE0F893440' using method 1 ...
05/01/2017 18:05:04:661 [08444] | INFO | > Succeeded.
05/01/2017 18:05:04:661 [08444] | INFO | Installing hook for '0x00007FFE40B2B920' with '0x00007FFE0F893110' using method 1 ...
05/01/2017 18:05:04:675 [08444] | INFO | > Succeeded.
05/01/2017 18:05:04:675 [08444] | INFO | Installing hook for '0x00007FFE40B38D00' with '0x00007FFE0F8931E0' using method 1 ...
05/01/2017 18:05:04:689 [08444] | INFO | > Succeeded.
05/01/2017 18:05:04:689 [08444] | INFO | Installing hook for '0x00007FFE40B2AFC0' with '0x00007FFE0F893730' using method 1 ...
05/01/2017 18:05:04:703 [08444] | INFO | > Succeeded.
05/01/2017 18:05:04:703 [08444] | INFO | Installing hook for '0x00007FFE40B380F0' with '0x00007FFE0F893820' using method 1 ...
05/01/2017 18:05:04:717 [08444] | INFO | > Succeeded.
05/01/2017 18:05:04:717 [08444] | INFO | Installing hook for '0x00007FFE40B2C520' with '0x00007FFE0F893540' using method 1 ...
05/01/2017 18:05:04:731 [08444] | INFO | > Succeeded.
05/01/2017 18:05:04:731 [08444] | INFO | Installing hook for '0x00007FFE40B2EA80' with '0x00007FFE0F893630' using method 1 ...
05/01/2017 18:05:04:745 [08444] | INFO | > Succeeded.
05/01/2017 18:05:05:065 [08444] | INFO | Installing delayed hooks for 'C:\WINDOWS\system32\dxgi.dll' ...
05/01/2017 18:05:05:065 [08444] | INFO | > Dumping matches in export table:
05/01/2017 18:05:05:065 [08444] | INFO | +
+
+
+
05/01/2017 18:05:05:065 [08444] | INFO | | Address | Ordinal | Name |
05/01/2017 18:05:05:065 [08444] | INFO | +
+
+
+
05/01/2017 18:05:05:065 [08444] | INFO | | 0x00007FFE3DEE5B30 | 10 | CreateDXGIFactory |
05/01/2017 18:05:05:065 [08444] | INFO | | 0x00007FFE3DEE5FF0 | 11 | CreateDXGIFactory1 |
05/01/2017 18:05:05:065 [08444] | INFO | | 0x00007FFE3DEE5C90 | 12 | CreateDXGIFactory2 |
05/01/2017 18:05:05:065 [08444] | INFO | | 0x00007FFE3DF007A0 | 13 | DXGID3D10CreateDevice |
05/01/2017 18:05:05:065 [08444] | INFO | | 0x00007FFE3DF007A0 | 14 | DXGID3D10CreateLayeredDevice |
05/01/2017 18:05:05:065 [08444] | INFO | | 0x00007FFE3DF25D80 | 16 | DXGID3D10GetLayeredDeviceSize |
05/01/2017 18:05:05:065 [08444] | INFO | | 0x00007FFE3DF007A0 | 17 | DXGID3D10RegisterLayers |
05/01/2017 18:05:05:065 [08444] | INFO | +
+
+
+
05/01/2017 18:05:05:065 [08444] | INFO | > Found 7 match(es). Installing ...
05/01/2017 18:05:05:065 [08444] | INFO | Installing hook for '0x00007FFE3DEE5B30' with '0x00007FFE0F86BF10' using method 0 ...
05/01/2017 18:05:05:065 [08444] | INFO | > Succeeded.
05/01/2017 18:05:05:065 [08444] | INFO | Installing hook for '0x00007FFE3DEE5FF0' with '0x00007FFE0F86C050' using method 0 ...
05/01/2017 18:05:05:065 [08444] | INFO | > Succeeded.
05/01/2017 18:05:05:065 [08444] | INFO | Installing hook for '0x00007FFE3DEE5C90' with '0x00007FFE0F86C290' using method 0 ...
05/01/2017 18:05:05:066 [08444] | INFO | > Succeeded.
05/01/2017 18:05:05:066 [08444] | INFO | Installing hook for '0x00007FFE3DF007A0' with '0x00007FFE0F86BE40' using method 0 ...
05/01/2017 18:05:05:066 [08444] | INFO | > Succeeded.
05/01/2017 18:05:05:066 [08444] | INFO | Installing hook for '0x00007FFE3DF007A0' with '0x00007FFE0F86BE90' using method 0 ...
05/01/2017 18:05:05:066 [08444] | INFO | > Succeeded.
05/01/2017 18:05:05:066 [08444] | INFO | Installing hook for '0x00007FFE3DF25D80' with '0x00007FFE0F86BEE0' using method 0 ...
05/01/2017 18:05:05:066 [08444] | INFO | > Succeeded.
05/01/2017 18:05:05:066 [08444] | INFO | Installing hook for '0x00007FFE3DF007A0' with '0x00007FFE0F86BEE0' using method 0 ...
05/01/2017 18:05:05:066 [08444] | INFO | > Succeeded.
05/01/2017 18:05:10:586 [13268] | INFO | Redirecting 'CreateDXGIFactory1({7B7166EC-21C7-44AE-B21A-C9AE321AE369}, 000000006B395D30)' ...
05/01/2017 18:05:10:593 [13268] | INFO | Installing hook for '0x00007FFE3DF2A0E0' with '0x00007FFE0F86A4E0' using method 2 ...
05/01/2017 18:05:10:593 [13268] | INFO | > Succeeded.
05/01/2017 18:05:10:593 [13268] | INFO | Installing hook for '0x00007FFE3DF2A550' with '0x00007FFE0F86AAD0' using method 2 ...
05/01/2017 18:05:10:593 [13268] | INFO | > Succeeded.
05/01/2017 18:05:10:593 [13268] | INFO | Installing hook for '0x00007FFE3DF2A3B0' with '0x00007FFE0F86B1A0' using method 2 ...
05/01/2017 18:05:10:593 [13268] | INFO | > Succeeded.
05/01/2017 18:05:10:593 [13268] | INFO | Installing hook for '0x00007FFE3DEE44B0' with '0x00007FFE0F86B800' using method 2 ...
05/01/2017 18:05:10:593 [13268] | INFO | > Succeeded.
05/01/2017 18:05:10:593 [13268] | INFO | Returning 'IDXGIFactory' object 000000006A8D5910
05/01/2017 18:05:10:684 [08444] | INFO | Redirecting 'RegisterClassExA(000000000014F0F0)' ...
05/01/2017 18:05:10:684 [08444] | INFO | > Adding 'CS_OWNDC' window class style flag to 'Battlefield 4'.
05/01/2017 18:05:10:828 [13268] | INFO | Redirecting 'RegisterRawInputDevices(000000006A4DF8F0, 1, 16)' ...
05/01/2017 18:05:10:828 [13268] | INFO | > Dumping device registration at index 0:
05/01/2017 18:05:10:828 [13268] | INFO | +
+
+
05/01/2017 18:05:10:828 [13268] | INFO | | Parameter | Value |
05/01/2017 18:05:10:828 [13268] | INFO | +
+
+
05/01/2017 18:05:10:828 [13268] | INFO | | UsagePage | 0x1 |
05/01/2017 18:05:10:828 [13268] | INFO | | Usage | 0x6 |
05/01/2017 18:05:10:828 [13268] | INFO | | Flags | 0 |
05/01/2017 18:05:10:828 [13268] | INFO | | TargetWindow | 00000000001D072A |
05/01/2017 18:05:10:828 [13268] | INFO | +
+
+
05/01/2017 18:05:10:828 [13268] | INFO | Redirecting 'RegisterRawInputDevices(000000006A4DF840, 1, 16)' ...
05/01/2017 18:05:10:828 [13268] | INFO | > Dumping device registration at index 0:
05/01/2017 18:05:10:828 [13268] | INFO | +
+
+
05/01/2017 18:05:10:828 [13268] | INFO | | Parameter | Value |
05/01/2017 18:05:10:828 [13268] | INFO | +
+
+
05/01/2017 18:05:10:828 [13268] | INFO | | UsagePage | 0x1 |
05/01/2017 18:05:10:828 [13268] | INFO | | Usage | 0x2 |
05/01/2017 18:05:10:828 [13268] | INFO | | Flags | 0x30 |
05/01/2017 18:05:10:829 [13268] | INFO | | TargetWindow | 00000000001D072A |
05/01/2017 18:05:10:829 [13268] | INFO | +
+
+
05/01/2017 18:05:10:829 [13268] | INFO | Redirecting 'D3D11CreateDevice(000000006A893530, 0, 0000000000000000, 0x80, 000000006A4DF6F0, 1, 7, 000000006A4DF6E8, 000000006A4DF6E0, 000000006A4DF6F8)' ...
05/01/2017 18:05:10:829 [13268] | INFO | > Passing on to 'D3D11CreateDeviceAndSwapChain':
05/01/2017 18:05:10:829 [13268] | INFO | Redirecting 'D3D11CreateDeviceAndSwapChain(000000006A893530, 0, 0000000000000000, 0x80, 000000006A4DF6F0, 1, 7, 0000000000000000, 0000000000000000, 000000006A4DF6E8, 000000006A4DF6E0, 000000006A4DF6F8)' ...
05/01/2017 18:05:10:844 [13268] | WARN | > 'D3D11CreateDeviceAndSwapChain' failed with error code 0x887a0004!
05/01/2017 18:05:10:845 [13268] | INFO | Redirecting 'D3D11CreateDevice(000000006A893530, 0, 0000000000000000, 0x80, 000000006A4DF458, 1, 7, 000000006A4DF6E8, 000000006A4DF6F0, 000000006A4DF6F8)' ...
05/01/2017 18:05:10:845 [13268] | INFO | > Passing on to 'D3D11CreateDeviceAndSwapChain':
05/01/2017 18:05:10:845 [13268] | INFO | Redirecting 'D3D11CreateDeviceAndSwapChain(000000006A893530, 0, 0000000000000000, 0x80, 000000006A4DF458, 1, 7, 0000000000000000, 0000000000000000, 000000006A4DF6E8, 000000006A4DF6F0, 000000006A4DF6F8)' ...
05/01/2017 18:05:10:874 [13268] | INFO | > Using feature level 0xb000.
05/01/2017 18:05:10:875 [13268] | INFO | Returning 'IDXGIDevice1' object 000000006A8A5A00
05/01/2017 18:05:10:875 [13268] | INFO | Returning 'ID3D11Device' object 000000006A8B0110
05/01/2017 18:05:10:875 [13268] | INFO | Returning 'ID3D11DeviceContext' object 000000006A8A54C0
05/01/2017 18:05:10:877 [13268] | INFO | Upgraded 'ID3D11Device' object 000000006A8B0110 to 'ID3D11Device1'.
05/01/2017 18:05:10:877 [13268] | INFO | Upgraded 'ID3D11DeviceContext' object 000000006A8A54C0 to 'ID3D11DeviceContext1'.
05/01/2017 18:05:10:880 [13268] | INFO | Redirecting 'IDXGIFactory::CreateSwapChain(000000006A8D5910, 000000006A8B0110, 000000006A4DF7F0, 000000006B399690)' ...
05/01/2017 18:05:10:880 [13268] | INFO | > Dumping swap chain description:
05/01/2017 18:05:10:880 [13268] | INFO | +
+
+
05/01/2017 18:05:10:880 [13268] | INFO | | Parameter | Value |
05/01/2017 18:05:10:880 [13268] | INFO | +
+
+
05/01/2017 18:05:10:880 [13268] | INFO | | Width | 1280 |
05/01/2017 18:05:10:880 [13268] | INFO | | Height | 720 |
05/01/2017 18:05:10:880 [13268] | INFO | | RefreshRate | 0 1 |
05/01/2017 18:05:10:880 [13268] | INFO | | Format | 28 |
05/01/2017 18:05:10:880 [13268] | INFO | | ScanlineOrdering | 0 |
05/01/2017 18:05:10:880 [13268] | INFO | | Scaling | 0 |
05/01/2017 18:05:10:880 [13268] | INFO | | SampleCount | 1 |
05/01/2017 18:05:10:880 [13268] | INFO | | SampleQuality | 0 |
05/01/2017 18:05:10:880 [13268] | INFO | | BufferUsage | 48 |
05/01/2017 18:05:10:880 [13268] | INFO | | BufferCount | 3 |
05/01/2017 18:05:10:880 [13268] | INFO | | OutputWindow | 00000000001D072A |
05/01/2017 18:05:10:880 [13268] | INFO | | Windowed | TRUE |
05/01/2017 18:05:10:880 [13268] | INFO | | SwapEffect | 0 |
05/01/2017 18:05:10:880 [13268] | INFO | | Flags | 0x2 |
05/01/2017 18:05:10:880 [13268] | INFO | +
+
+
05/01/2017 18:05:10:881 [13268] | INFO | Redirecting 'D3D11CreateDevice(000000006C55AAD0, 0, 0000000000000000, 0x80, 000000006A4DEB20, 1, 7, 000000006A4DEAD0, 0000000000000000, 0000000000000000)' ...
05/01/2017 18:05:10:881 [13268] | INFO | > Passing on to 'D3D11CreateDeviceAndSwapChain':
05/01/2017 18:05:10:881 [13268] | INFO | Redirecting 'D3D11CreateDeviceAndSwapChain(000000006C55AAD0, 0, 0000000000000000, 0x80, 000000006A4DEB20, 1, 7, 0000000000000000, 0000000000000000, 000000006A4DEAD0, 0000000000000000, 0000000000000000)' ...
05/01/2017 18:05:10:890 [13268] | INFO | > Using feature level 0xb000.
05/01/2017 18:05:10:890 [13268] | INFO | Returning 'IDXGIDevice1' object 000000006C59FC60
05/01/2017 18:05:10:890 [13268] | INFO | Returning 'ID3D11Device' object 000000006A8AF850

Thanks.

**Comment by crosire** [comment]
Disable the Origin overlay. And use the forum for the sort of things.

**Comment by Benji-13** [comment]
The origin overlay is disabled. I have looked  at every thread I can find. This is either a genuine bug or an incompatibility that no one knows about.
