### ISSUE TITLE
Feature Request: xBRZ/ScaleFX

### ISSUE THREAD

**Issue by waltzz92** [crosire/reshade#8]
Hi, I am requesting 2d upscalers. It would be nice for Reshade to have either xBRZ or ScaleFX as an alternative to HQ4x. Thanks for this awesome program.

Source for xBRZ:
https://sourceforge.net/projects/xbrz/

Source for ScaleFX
https://github.com/libretro/common-shaders/tree/master/scalefx

**Comment by crosire** [comment]
This is the reshade repository, not reshade-shaders.

**Comment by waltzz92** [comment]
How can I add this request to the reshade-shaders repository? I could not find an Issues tab there.

**Comment by crosire** [comment]
You can't. Use the forum.
